services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=app-db'
      - 'POSTGRES_PASSWORD=J8v2pLx9wQz1'
      - 'POSTGRES_USER=app-user'
    ports:
      - '5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
