server:
  port: 8081
spring:
  application:
    name: spring-boot-template
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
logging:
  level:
    org:
      springframework:
        security: trace
